export const publicComponentCoverage = {
  actionsLayout: [
    'Button',
    'IconButton',
    'Link',
    'Surface',
    'Card',
    'Panel',
    'Stack',
    'Grid',
    'Divider',
    'PageHeader',
    'AppShell',
  ],
  forms: [
    'Field',
    'Input',
    'PasswordInput',
    'Textarea',
    'NativeSelect',
    'Select',
    'Combobox',
    'Checkbox',
    'RadioGroup',
    'RatingInput',
    'Switch',
    'SegmentedControl',
    'FileUpload',
    'MediaUpload',
  ],
  navigation: ['Tabs', 'BottomNav', 'Sidebar', 'Breadcrumbs', 'Pagination', 'Accordion'],
  sections: [
    'SectionCard',
    'ChoiceCardGroup',
    'SettingsGroup',
    'SettingsRow',
    'KeyValueGrid',
    'DisclosureRow',
  ],
  feedback: [
    'Badge',
    'SeverityBadge',
    'StatusBadge',
    'DotLabel',
    'Alert',
    'Toast',
    'Progress',
    'Skeleton',
    'Loader',
    'EmptyState',
    'ErrorState',
    'PermissionState',
    'OfflineBanner',
    'ConflictState',
  ],
  overlays: ['Tooltip', 'Popover', 'Menu', 'Dialog', 'ConfirmDialog', 'Drawer', 'BottomSheet'],
  data: ['DataTable', 'StatCard', 'Timeline', 'Avatar', 'AnimatedNumber'],
  foundations: ['DesktopOnlyGate', 'OfflineFallback'],
} as const;

export const publicStateCoverage = {
  actions: ['default', 'hover', 'pressed', 'focus-visible', 'disabled', 'loading', 'danger'],
  fields: ['empty', 'filled', 'helper', 'invalid', 'disabled', 'read-only'],
  selection: ['checked', 'unchecked', 'selected', 'controlled', 'uncontrolled'],
  overlays: ['open', 'close', 'Escape', 'outside-click', 'focus-trap', 'focus-return'],
  feedback: ['loading', 'empty', 'error', 'permission', 'offline', 'conflict', 'toast'],
  motion: ['standard', 'emphasized', 'enter', 'exit', 'reduced-motion'],
} as const;
